# Generated by Django 3.0.1 on 2022-04-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVO',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='category_name', default='', max_length=255)),
                ('category_description', models.TextField(db_column='category_description', default='', max_length=255))
            ],
            options={
                'db_table': 'category_table',
            },
        ),
    ]
