# Generated by Django 3.0.1 on 2022-05-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryVO',
            fields=[
                ('sub_category_id', models.AutoField(db_column='sub_category_id', primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(db_column='sub_category_name', default='', max_length=255)),
                ('sub_category_description', models.TextField(db_column='sub_category_description', max_length=255)),
                ('sub_category_category_vo',
                 models.ForeignKey(db_column='sub_category_category_id', on_delete=django.db.models.deletion.CASCADE,
                                   to='base.CategoryVO')),
            ],
            options={
                'db_table': 'sub_category_table',
            },
        ),
    ]
