# Generated by Django 3.0.1 on 2022-05-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_productvo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginVO',
            fields=[
                ('login_id', models.AutoField(db_column='login_id', primary_key=True, serialize=False)),
                ('login_name', models.CharField(db_column='login_name', default='', max_length=255)),
                ('login_password', models.CharField(db_column='login_password', max_length=255)),
                ('login_role', models.CharField(db_column='login_role', max_length=255)),
                ('login_status', models.CharField(db_column='login_status', max_length=255)),
                ('login_secret_key', models.CharField(db_column='login_secret_key', max_length=255)),
            ],
            options={
                'db_table': 'login_table',
            },
        ),
        migrations.CreateModel(
            name='UserVO',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(db_column='user_first_name', default='', max_length=255)),
                ('user_last_name', models.CharField(db_column='user_last_name', max_length=255)),
                ('user_login_vo', models.ForeignKey(db_column='user_login_vo', on_delete=django.db.models.deletion.CASCADE, to='base.LoginVO')),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
